### ISSUE TITLE
Beoordeling opdracht 1.2

### ISSUE THREAD

**Issue by KoopReynders** [CountNick/browser-technologies-1920#1]
### Criteria

- een beschrijving van alle features die je hebt getest

> Goed. Leuk die screens en foto's. Ik snap de toevoeging van de projectbeschrijving van je OBA opdracht niet. 

- beschrijf hoe je de problemen hebt opgelost, of hoe je dit zou oplossen (met todo’s) als je genoeg tijd en budget zou hebben

> Ook prima

- een beschrijving van de Devices en browsers waar je op hebt getest

> Keurig

- een beschrijving van de screenreader test

> Prima. Heb je ook een audiofile? Ik ben benieuwd hoe dit klinkt

**Comment by KoopReynders** [comment]
De opbouw/structuur van je readme is een beetje rommelig. Kop, staart, help de lezer?

**Comment by CountNick** [comment]
Heb de opdracht nu in de wiki gezet om het iets overzichtelijker te maken. Nee ik heb geen audiofile van de screenreader test..
